### ISSUE TITLE
Link to freesurfer data on S3

### ISSUE THREAD

**Issue by r03ert0** [preprocessed-connectomes-project/abide#10]
Hello,
I tried this link to get data from S3:
https://s3.amazonaws.com/fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/50002/surf/lh.pial
But I get an error. Am I doing something wrong?

Here's the error:
````
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/50002/surf/lh.pial</Key>
<RequestId>809A3F0391F8BD8E</RequestId>
<HostId>fYcV661vrZd4jjhRa5Qo5bHLiTxww8+qsiBoe4t5CMyNFRCUzPT4in+QPSqS+CmhRRMphsUS6cQ=</HostId>
</Error>
````

**Comment by r03ert0** [comment]
I found the issue. The correct Subject ID should include the abbreviation of the scanning centre, and the leading zeros, like this:

https://s3.amazonaws.com/fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Pitt_0050002/surf/lh.pial

Probably the documentation has to be updated.

**Comment by stymy** [comment]
Hi Roberto,

The documentation is unclear, but the [File ID] column of the summary spreadsheet* should be useful to construct the download link.

The link to the python download script is outdated, but a new version exists here:
https://github.com/preprocessed-connectomes-project/abide/blob/master/download_abide_preproc.py

old version:
https://github.com/ccraddock/abide/blob/master/get_s3_paths.py

*available here: https://s3.amazonaws.com/fcp-indi/data/Projects/ABIDE_Initiative/Phenotypic_V1_0b_preprocessed1.csv

**Comment by r03ert0** [comment]
thank you!
I've managed to download all the .white and .pial surfaces. More news soon
:)
cheers,
roberto
